# Generated by Django 4.0.3 on 2023-08-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userAge',
            new_name='user_age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userRegDate',
            new_name='user_reg_date',
        ),
        migrations.RenameField(
            model_name='userimage',
            old_name='imageRegDate',
            new_name='image_reg_date',
        ),
        migrations.AddField(
            model_name='userimage',
            name='path',
            field=models.FilePathField(default=1),
            preserve_default=False,
        ),
    ]
