# Generated by Django 4.0.3 on 2023-08-25 02:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userage_user_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
