# Generated by Django 4.0.3 on 2023-08-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='path',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='uuid',
        ),
    ]
