# Generated by Django 4.0.3 on 2023-08-25 05:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userimage_path_remove_userimage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image_url',
            field=models.ImageField(default=1, upload_to=users.models.upload_to),
            preserve_default=False,
        ),
    ]
